Repository AY2324S2-CS2113-T15-3/tp, pull requests merged in 2024-03, with the labels that each got.

#17 Add help menu and logo
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.High

#20 Add expense parsing and formatting for expense objects.
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/ExpenseAdder.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Story, priority.High

#27 JUnit test for help functionality
  src/test/java/seedu/duke/HelpTest.java
Labels: type.Enhancement, priority.High

#30 Implement exception for adding member to group
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/GroupTest.java
Labels: priority.High

#34 Amend group functionality
  src/main/java/seedu/duke/Balance.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/ExpensesException.java
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/BalanceTest.java
  src/test/java/seedu/duke/ExpenseTest.java
  src/test/java/seedu/duke/GroupTest.java
Labels: type.Story

#37 Fix checkstyle error
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.High

#45 Addded use of optional to handle null and fixed checkstyle
  docs/AboutUs.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/GroupTest.java
Labels: type.Task, priority.High

#48 Fix optional
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/GroupCommand.java
  src/test/java/seedu/duke/AddUserTest.java
  src/test/java/seedu/duke/GroupTest.java
Labels: type.Task, priority.High

#50 Add member feature in DG
  docs/DeveloperGuide.md
Labels: priority.High

#66 Add UniversalExceptions.java
  src/main/java/seedu/duke/UniversalExceptions.java
Labels: type.Enhancement

#68 Add description and unequal split to Expenses
  build.gradle
  src/main/java/seedu/duke/Balance.java
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/BalanceTest.java
  src/test/java/seedu/duke/ExpenseTest.java
Labels: type.Enhancement, priority.High

#64 Implement database
  .gitignore
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/Group.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/exceptions/GroupLoadException.java
  src/main/java/seedu/duke/exceptions/GroupSaveException.java
  src/main/java/seedu/duke/storage/FileIO.java
  src/main/java/seedu/duke/storage/FileIOImpl.java
  src/main/java/seedu/duke/storage/GroupFilePath.java
  src/main/java/seedu/duke/storage/GroupStorage.java
  src/test/java/seedu/duke/storage/GroupStorageTest.java
Labels: priority.High

#71 Gambling
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/Luck.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SlotMachine.java
  src/main/java/seedu/duke/storage/GroupStorage.java
  src/test/java/seedu/duke/HelpTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#72 update pair from javafx to inbuilt class and fix issue with equal split
  src/main/java/seedu/duke/Expense.java
  src/main/java/seedu/duke/storage/GroupStorage.java
Labels: type.Bug, priority.High
